name: Build and Release

on:
  push:
    paths-ignore:
        - "documentation/**"
    branches:
      - misterya
  workflow_dispatch:

jobs:
  build:
    permissions:
        contents: write
    name: Build and Release
    runs-on: ubuntu-latest
    outputs:
        MMS_VERSION: ${{ steps.MMS_VERSION.outputs.MMS_VERSION }}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '10.0'

      - name: Get MMS Version
        id: MMS_VERSION
        run: |
            MMS_VERSION=$(grep -oP 'ModuleVersion\s*=>\s*"\K[^"]*' MatchZy.cs)
            echo "MMS_VERSION=$MMS_VERSION" >> $GITHUB_ENV

      - name: Build and Release Artifacts
        run: |
          CSSHARP_VERSION=$(grep -Po '<PackageReference Include="CounterStrikeSharp.API" Version="\K\d+(\.\d+)*' MatchZy.csproj)
          echo "Creating MMS base package with version: $MMS_VERSION"
          dotnet publish -o package/addons/counterstrikesharp/plugins/MMS
          cp -r cfg package 
          cd package && zip -q -r ../MMS-$MMS_VERSION.zip * && cd ..

          echo "Creating package with CounterStrikeSharp (CSSharp) v$CSSHARP_VERSION for Linux"
          cd package/
          [ -e addons/counterstrikesharp ] && rm -rf addons/counterstrikesharp && echo "CounterStrikeSharp removed" || echo "old CounterStrikeSharp not found"
          curl -s https://api.github.com/repos/roflmuffin/CounterStrikeSharp/releases/tags/v$CSSHARP_VERSION |
              grep "/counterstrikesharp-with-runtime-linux-$CSSHARP_VERSION" |
              cut -d : -f 2,3 |
              tr -d \" |
              head -n 1 |
              wget -O cssharp-linux.zip -qi -
          unzip -o cssharp-linux.zip -d .
          rm cssharp-linux.zip
          cd ../

          dotnet publish -o package/addons/counterstrikesharp/plugins/MMS

          cd package && zip -q -r ../MMS-$MMS_VERSION-with-cssharp-linux.zip * && cd ..

      - name: Create Release
        id: create_release
        uses: softprops/action-gh-release@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          name: MMS ${{ env.MMS_VERSION }}
          tag_name: ${{ env.MMS_VERSION }}
          body: |
            Voir [`CHANGELOG.md`](https://github.com/c3drick0s/MisteryA-Match-System/blob/misterya/CHANGELOG.md) pour le détail des modifications.

            **Installation :**
            Extraire le contenu de `MMS-${{ env.MMS_VERSION }}.zip` dans le répertoire `csgo/` du serveur.
            Prérequis : Metamod et CounterStrikeSharp doivent être installés.

            Le zip `MMS-${{ env.MMS_VERSION }}-with-cssharp-linux.zip` inclut CounterStrikeSharp pour Linux.
          draft: false
          prerelease: false
          files: |
            MMS-${{ env.MMS_VERSION }}.zip
            MMS-${{ env.MMS_VERSION }}-with-cssharp-linux.zip